name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Бэкенд (Go)
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Install backend dependencies
        run: cd backend && go mod download
        
      - name: Build backend
        run: cd backend && go build ./...
        
      # Фронтенд (просто копирование файлов, без сборки)
      - name: Prepare frontend
        run: |
          mkdir -p backend/public
          cp -R frontend/* backend/public/
          echo "✅ Frontend ready!" 
  
  test-lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: Run tests
        run: cd backend && make test
        
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: backend
          args: --timeout=5m
