name: CI

on:
  push:    { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Backend
      - uses: actions/setup-go@v5
        with: { go-version: '1.21' }
      - run: cd backend && go mod download && go build ./...

      # Frontend
      - uses: actions/setup-node@v4
        with: { node-version: '18' }
      - run: cd frontend && npm ci && npm run build

  test-lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.21' }
      - run: cd backend && go mod download && make test
      - uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          working-directory: backend
          args: --timeout=5m
